Numpy 是非常强大的 Python 数值计算库。你可以参阅以下资源：

* [Numpy 官方教程](https://docs.scipy.org/doc/numpy/user/quickstart.html)
* [CS231N Numpy](http://cs231n.github.io/python-numpy-tutorial/)
* [Numpy 中文文档](https://www.numpy.org.cn/index.html)

# ndaray 对象

Numpy 包的核心是ndarray对象。NumPy数组 和 标准Python Array（数组） 之间有几个重要的区别：

- NumPy数组在创建时具有固定的大小，与Python的原生数组对象（可以动态增长）不同。 更改ndarray的大小将创建一个新数组并删除原来的数组。
- NumPy数组中的元素都需要具有相同的数据类型，因此在内存中的大小相同。 
- NumPy数组有助于对大量数据进行高级数学和其他类型的操作。
- 越来越多的基于Python的科学和数学软件包使用NumPy数组;

Numpy 优势

- Python 代码更加简介，运算调用预编译的 C 代码速度更快
- 矢量化代码更简洁，更易于阅读

# ndarray 属性

In [28]:
import numpy as np

# Array properties
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(type(a)) # >>><class 'numpy.ndarray'>
print(a.dtype) # >>>int64
print(a.size) # >>>25
print(a.shape) # >>>(5, 5)
print(a.itemsize) # >>>8
print(a.ndim) # >>>2
print(a.nbytes) # >>>200

<class 'numpy.ndarray'>
int64
25
(5, 5)
8
2
200


# ndarray 的创建，一维和二维

In [6]:
import numpy as np
# 定义一维 numpy
arr = np.array([1,2,3,4,5])
# 可以整个输出数组，指定索引输出，数组形状
print(arr)
print(arr[0])
print(arr[3])
print(arr.shape)

# 修改元素
arr[0] = 0
print(arr)

# 这些操作都挺符合逻辑，不难掌握

[1 2 3 4 5]
1
4
(5,)
[0 2 3 4 5]


In [5]:
import numpy as np

# 一维数组，长度为5，元素都为0
my_new_array = np.zeros((5)) 
print(my_new_array)

# 一维数组，长度为5，元素都为1
my_new_array = np.ones((5))
print(my_new_array)

# 一维数组，长度为5，元素0-1随机
my_new_array = np.random.random((5))
print(my_new_array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.52080146 0.03565074 0.35460495 0.68039326 0.75247859]


**前面定义一维数组还是比较简单的，之后看看定义二维数组的方法**

In [29]:
import numpy as np

my_2d_array = np.zeros((2,3))
print(my_2d_array)

print("*****************************")

my_array = np.array([[3,4],[5,7]])
print(my_array)

my_array = np.array([(3,4),(5,7)])
print(my_array)

print("*****************************")

print(my_array[1,1])
# 多维数组切片（包左不包右）
print(my_array[:,1])
print(my_array.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
*****************************
[[3 4]
 [5 7]]
[[3 4]
 [5 7]]
*****************************
7
[4 7]
(2, 2)


In [27]:
import numpy as np

# np.arrange() 返回的是数组而不是列表
print(np.arange(10,35, 3))
print(np.arange(10,35, 3).reshape(3,3))

[10 13 16 19 22 25 28 31 34]
[[10 13 16]
 [19 22 25]
 [28 31 34]]


**此外还有数组创建还有更多的方式**

> array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, numpy.random.rand, numpy.random.randn, fromfunction, fromfile

# 打印数组

当你打印数组时，NumPy以与嵌套列表类似的方式显示它，但是具有以下布局：

- 最后一个轴从左到右打印
- 倒数第二个从上到下打印
- 其余的也从上到下打印，每个切片与下一个用空行分开。

In [32]:
import numpy as np

# 一维
a = np.arange(6)
print(a)

# 二维
b = np.arange(12).reshape(3,4)
print(b)

# 三维
c = np.arange(24).reshape(2,3,4)
print(c)

# 数组过大打印时将会跳过中间部分
print(np.arange(10000))

[0 1 2 3 4 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[   0    1    2 ... 9997 9998 9999]


ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

# Numpy 做算数运算

四则运算演示

In [19]:
import numpy as np

a = np.array([[3.5,6.4],[4,8.1]])
b = np.array([[10.5,6.0],[4,8.1]])

# 加减乘除四则运算
print(a + b)
print(a - b)
print(a * b)
print(a / b)
# 矩阵乘法
print(a.dot(b))

[[14.  12.4]
 [ 8.  16.2]]
[[-7.   0.4]
 [ 0.   0. ]]
[[36.75 38.4 ]
 [16.   65.61]]
[[0.33333333 1.06666667]
 [1.         1.        ]]
[[62.35 72.84]
 [74.4  89.61]]


In [20]:
# 一些函数

import numpy as np

# dot, sum, min, max, cumsum
a = np.arange(10)

print(a.sum()) # >>>45
print(a.min()) # >>>0
print(a.max()) # >>>9
print(a.cumsum()) # >>>[ 0  1  3  6 10 15 21 28 36 45]

45
0
9
[ 0  1  3  6 10 15 21 28 36 45]
